spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5003/inventory-service
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


